import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  console.log("Hello there");
  return {
    props: {
      coffeeStores: coffeeStoresData,
    },
  }
}

export default function Home(props) {
  console.log(props);

  const handleBannerBtnClick = () => {
    console.log("test");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="Discover shops nearby"
          handleOnClick={handleBannerBtnClick}
        />
        <h2>Nearby stores</h2>
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
          return (
            
            <Card
              key={coffeeStore.id}
              className={styles.card}
              name={coffeeStore.name}
              href={`/coffee-shop/${coffeeStore.id}`}
              imgURL={coffeeStore.imgUrl}
              alt={coffeeStore.name}
            />)
          })}
        </div>
      </main>
    </div>
  );
}
