import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import Card from "../components/Card";
import coffeeStoresData from "../data/coffee-stores.json";
import { fetchCoffeStores } from "../lib/coffee-stores";
import useTrackLocation from "../hooks/use-track-location";

export async function getStaticProps(context) {
  const coffeeStores = await fetchCoffeStores();
  console.log(coffeeStores);

  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home(props) {
  console.log(props);

  const { handleTrackLocation, latLong, locationErrorMesg } =
    useTrackLocation();

  console.log({ latLong, locationErrorMesg });

  const handleBannerBtnClick = () => {
    console.log("test");
    handleTrackLocation();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="Discover shops nearby"
          handleOnClick={handleBannerBtnClick}
        />
        <h2>Nearby stores</h2>
        <div className={styles.cardLayout}>
          {props.coffeeStores.map((coffeeStore) => {
            return (
              <Card
                key={coffeeStore.id}
                className={styles.card}
                name={coffeeStore.name}
                href={`/coffee-shop/${coffeeStore.id}`}
                imgUrl={
                  coffeeStore.imgUrl ||
                  "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                }
                alt={coffeeStore.name}
              />
            );
          })}
        </div>
      </main>
    </div>
  );
}
